// Generated by CoffeeScript 1.7.1
(function() {
  $('#pirates').click(function() {
    return alert("give me your money");
  });

  $('#abandonShip').click(function() {
    return alert("sharks");
  });

}).call(this);

//# sourceMappingURL=main.map
